# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Full name.', max_length=50, unique=True)),
                ('iq', models.PositiveSmallIntegerField(help_text=b'Just pretend.')),
            ],
        ),
    ]
